### ISSUE TITLE
[Bug]: Stackscript RFC3339 error

### ISSUE THREAD

**Issue by ashtarcommunications** [linode/terraform-provider-linode#1372]
### Terraform Version

Terraform v1.3.7 on linux_amd64

### Linode Provider Version

v2.18.0

### Effected Terraform Resources

linode_stackscript

### Terraform Config Files

```terraform
resource "linode_stackscript" "test" {
    label = "test"
    description = "Test stackscript"
    script = <<EOF
#!/bin/bash
echo "test"
EOF
    images = ["any/all"]
    rev_note = "v1"
}
```

### Debug Output

Error: Invalid RFC3339 String Value 
│   with linode_stackscript.test,
│   on test.tf line 1, in resource "linode_stackscript" "test":
│    1: resource "linode_stackscript" "test" {
│ 
│ A string value was provided that is not valid RFC3339 string format.
│ 
│ Given Value: 2023-08-12 14:41:04 +0000 UTC
│ Error: parsing time "2023-08-12 14:41:04 +0000 UTC" as "2006-01-02T15:04:05Z07:00": cannot parse " 14:41:04 +0000 UTC" as "T"

### Expected Behavior

Should correctly interpret the timestamps

### Actual Behavior

After upgrading from v1 to v2.18.0, I'm getting this error on plan/apply for an existing state file. There is no date/time included in the resource config, so this appears to be a problem with parsing the created/updated timestamp in the existing state file. Manually updating timestamps in the state file to match RFC3339 appears to resolve the error, but I would have expected this to either be handled automatically or documented somewhere.

For now, the workaround of manually editing the state file appears to be sufficient, so feel free to close this if that's the recommended approach to a v1 -> v2 upgrade.

### Steps to Reproduce

Use existing state file for a stackscript resource created before v2, using a non-RFC3339 timestamp in the "created" and "updated" fields.

Apologies if there are upgrade/migration instructions somewhere for v2 of the provider that we didn't follow, I couldn't find anything in the docs.

**Comment by zliang-akamai** [comment]
Hi @ashtarcommunications, thank you for the feedback! We successfully reproduced the bug and is working on fixing it.

The root cause of the bug was that we changed the time format for `created` and `updated` attributes of the stackscript resource to `RFC3339` in `v2.0.0` and then added a `CustomType` with RFC3339 validation logic in `v2.16.0`.

As a workaround, you may try to upgrade from `v1.x.x` to `v2.15.0` and run `terraform refresh`. And then you will be able to upgrade to the latest version (`>=v2.16.0`) without any error.

We are implementing a state upgrade logic to make Terraform automatically update the time format without disturbing the practitioners, and we expect to release it in the next version of the provider.

Let us know if you have any question or concern. Thank you again!
