### ISSUE TITLE
[Bug]: Terraform is deleting the cluster node pools on every apply

### ISSUE THREAD

**Issue by dineshsaathe** [linode/terraform-provider-linode#1384]
### Terraform Version

v1.5.7

### Linode Provider Version

2.18.0

### Effected Terraform Resources

linode_lke_cluster
linode_lke_node_pool

### Terraform Config Files

```terraform
resource "linode_lke_cluster" "cluster" {
  label       = local.cluster_name
  k8s_version = "1.29"
  region      = "ap-west"

  pool {
    type  = "g6-standard-2"
    autoscaler {
      min = 1
      max = 1
    }
  }
}


resource "linode_lke_node_pool" "test-pool" {
  cluster_id  = linode_lke_cluster.cluster.id
  type        = "g6-standard-4"
  node_count  = 1
  autoscaler {
    min = 1
    max = 10
  }
 tags = [local.external_pool_tag]
}

resource "linode_lke_node_pool" "testsecond-pool" {
  cluster_id  = linode_lke_cluster.cluster.id
  type        = "g6-standard-2"
  node_count  = 3
  autoscaler {
    min = 3
    max = 10
  }
 tags = [local.external_pool_tag]
}

locals {
  external_pool_tag = "external"
}
```

### Expected Behavior

Terraform plan should show "no changes" if there are no changes.

### Actual Behavior

Terraform plan is showing deleting node pools on each and every run.

### Steps to Reproduce

terraform plan

**Comment by zliang-akamai** [comment]
Hi @dineshsaathe, I think you would need to set:
- `external_pool_tags` attribute of the `linode_lke_cluster` resource as `external_pool_tags = [local.external_pool_tag]`
- `tag` attribute of the `linode_lke_node_pool` resource as `tags = [local.external_pool_tag]`

These are for declaring that the node pool is external managed by the `linode_lke_node_pool` resource (rather than a nested pool of the `linode_lke_cluster` resource), so the `linode_lke_cluster` resource won't update or delete them except when the cluster itself is being deleted.

You can checkout our latest document for the full example: https://registry.terraform.io/providers/linode/linode/latest/docs/resources/lke_cluster#externally-managed-node-pools

Feel free to let us know if you have any question or concern.

**Comment by dineshsaathe** [comment]
@zliang-akamai Sorry for incomplete code, actually "tags = [local.external_pool_tag]" is already set in my pool configure but while creating this issue, it got removed somehow in editing. So even after adding this external tag, I can see node pool are getting deleted on next apply.

`    linode = {
      source  = "linode/linode"
      version = "2.18.0"
    }`

**Comment by dineshsaathe** [comment]
@zliang-akamai I tried to add it now in `linode_lke_cluster,` but it seems pool will get recreated then only external tag will get apply.

**Comment by zliang-akamai** [comment]
@dineshsaathe You may have to recreate them to get things sorted. After `external_pool_tags` being applied into the Terraform state, the cluster resource will ignore pools created by the pool resources in the next apply.
