### ISSUE TITLE
[Bug]: blocker -- checksum list has unexpected SHA-256 hash

### ISSUE THREAD

**Issue by mlabbe** [linode/terraform-provider-linode#1453]
### Terraform Version

OpenTofu v1.7.2 via snap

### Linode Provider Version

2.21.1

### Effected Terraform Resources

init

### Terraform Config Files

provider "linode" {} 

### Debug Output

│ Error: Failed to install provider
│
│ Error while installing linode/linode v2.21.1: checksum list has unexpected SHA-256 hash e43ff2fb6f44f72d1b1f42bbece00c7668f46a94d8770f079e1c0a8d1ba89807
│ (expected 4432414ffba160577dda7f94d866c44ecdd6d4c0a0e02f1e7cbb295974d60b7a)
╵

### Expected Behavior

sha match

### Actual Behavior

sha no match

### Steps to Reproduce

This statred occurring since the latest version of Linode provider was updated (yesterday)

**Comment by mlabbe** [comment]
Workaround of locking it to an earlier version works

terraform {
  required_providers {
    linode = {
      source = "linode/linode"
      version = "2.21.0"
    }

**Comment by zliang-akamai** [comment]
Hi @mlabbe, the issue was due to a recreation of `2.21.1` release on GitHub due to a HashiCorp TF registry sync issue.

We are in [communication](https://github.com/opentofu/registry/issues/633) with OpenTofu team to re-sync `2.21.1` on OpenTofu registry, and we also created an new patch `2.21.2` to sync up everything.

Hope this help! Let us know if you have any question.
