### ISSUE TITLE
Argument `linode_id` from resource `linode_nodebalancer` is not expected there

### ISSUE THREAD

**Issue by Miknuki** [linode/terraform-provider-linode#308]
### Terraform Version
v0.13.6

❯ terraform -v
Terraform v0.13.6

### Effected Resource(s)

- linode_nodebalancer

### Terraform Configuration Files
```terraform
resource "linode_nodebalancer" "test-nb" {
    region                      = var.region
    label                         = var.label
    client_conn_throttle = var.client_conn_throttle
    tags                          = var.tags
    linode_id                  = var.linode_id
}
```

### Debug Output

Error: Unsupported argument

  on main.tf line 6, in resource "linode_nodebalancer" "infracode-nb":
   6:     linode_id            = var.linode_id

An argument named "linode_id" is not expected here.

### Expected Behavior

To map a linode_id to the NodeBalancer.

**Comment by LBGarber** [comment]
Hello! 

Thanks for the report! It looks like our NodeBalancer documentation is currently incorrect. In order to attach a Linode to a NodeBalancer, you can do something like this:
```hcl
resource "linode_nodebalancer" "test-nb" {
  label = var.label
  region = var.region
  client_conn_throttle = var.client_conn_throttle
  tags = var.tags
}

resource "linode_nodebalancer_config" "test-nb-config" {
  nodebalancer_id = linode_nodebalancer.test-nb.id
  port = 80
  protocol = "http"
}

resource "linode_nodebalancer_node" "test-nb-node" {
  nodebalancer_id = linode_nodebalancer.test-nb.id
  config_id = linode_nodebalancer_config.test-nb-config.id
  address = "private_ip_of_linode:80"
  label = "test-nb-node"
}
```
You can also see our [nodebalancer_node resource docs](https://registry.terraform.io/providers/linode/linode/latest/docs/resources/nodebalancer_node) and our [NodeBalancer API docs](https://www.linode.com/docs/api/nodebalancers/). Let us know if you have any other questions! :smile:

**Comment by Miknuki** [comment]
Hello,

Thank you very much for the Information!

I will close the issue.
