### ISSUE TITLE
[Bug]: Forces replacement after import of linode_instance

### ISSUE THREAD

**Issue by danmichaelo** [linode/terraform-provider-linode#533]
### Terraform Version

Terraform v1.0.10 on darwin_amd64

### Linode Provider Version

version = "1.22.0"

### Effected Terraform Resources

linode_instance

### Expected Behavior

After importing a Linode I would expect to be able to run `terraform apply` without the node being replaced.

### Actual Behavior

Terraform suggests to replace the node based on `authorized_keys` (did not change), `image` (did not change) and `root_pass` (did not change). 

```
  # linode_instance.REDACTED_NAME[0] must be replaced
-/+ resource "linode_instance" "REDACTED_NAME" {
      + authorized_keys    = [
          + "ssh-ed25519 (redacted) -- Comment",
        ] # forces replacement
      ~ backups            = [
          - {
              - enabled  = true
              - schedule = [
                  - {
                      - day    = "Scheduling"
                      - window = "Scheduling"
                    },
                ]
            },
        ] -> (known after apply)
      ~ boot_config_label  = "My Debian 10 Disk Profile" -> (known after apply)
      ~ id                 = "(REDACTED)" -> (known after apply)
      + image              = "linode/debian10" # forces replacement
      ~ ip_address         = "(REDACTED)" -> (known after apply)
      ~ ipv4               = [
          - "(REDACTED)",
          - "(REDACTED)",
        ] -> (known after apply)
      ~ ipv6               = "(REDACTED)" -> (known after apply)
      ~ private_ip_address = "(REDACTED)" -> (known after apply)
      + root_pass          = (sensitive value) # forces replacement
      ~ specs              = [
...
```

### Steps to Reproduce

1. Create a Linode using Terraform
2. Forget it using `terraform state rm {NAME}`
3. Re-import it using `terraform import linode_instance.instance_name[0] Linode_ID`
4. `terraform apply`

**Comment by LBGarber** [comment]
Hello, thanks for the report!

This seems to be a symptom of fields such as `root_pass` not being stored in the state during a read. This is due to these fields not being returned by the Linode API after the initial creation of a Linode, which makes it difficult to infer whether or not a change has occurred after an import.

I'll investigate possible workarounds for this issue and keep you updated!

**Comment by LBGarber** [comment]
Unfortunately, there doesn't seem to be a clean and reliable solution to this issue for the time being due to the nature of the bug. I'll add this to our internal tracker and let you know if there are any related developments down the line.

In the meantime, feel free to submit any other issues you run into! :smile:
