### ISSUE TITLE
[Feature]: Changing instance type i.e scalling up does not resize the disk

### ISSUE THREAD

**Issue by gathecageorge** [linode/terraform-provider-linode#592]
### Description

It would be better if scaling up an instance to automatically resize the disk up for the new type.
Incase of scaling down, 2 scenarios can be possible check used up space if less than new type size then resize otherwise throw error. Or don't scale disk at all during scale down

### New or Affected Terraform Resources

linode_instances

### Potential Terraform Configuration

resource "linode_instance" "web" {
    label = "simple_instance"
    image = "linode/ubuntu18.04"
    region = "us-central"
    type = "g6-standard-1"
   .......others

Change type to "g6-standard-2" should scale disk also

**Comment by LBGarber** [comment]
Hello! Thanks for the suggestion 🙂 

This functionality has been added in PR #593 and will be available in our next release. Once the release is out, your disks will be upsized along with your Linode if `resize_disk = true`. Currently we do not allow the automatic downsizing of disks, but upsizing should work as expected. If you need to downsize a disk, consider using [explicit disks](https://registry.terraform.io/providers/linode/linode/latest/docs/resources/instance#linode-instance-with-explicit-configs-and-disks). Keep in mind that disks _must_ be implicit in order to be automatically resized. 

Feel free to leave any other feedback you may have!
