### ISSUE TITLE
[Bug]: DataSource Images - Image Output format not appropriate

### ISSUE THREAD

**Issue by jveraduran** [linode/terraform-provider-linode#695]
### Terraform Version

Terraform v1.2.4 on darwin_amd64

### Linode Provider Version

version = "1.29.2"

### Effected Terraform Resources

linode_images

### Terraform Config Files

```
data "linode_images" "bastion" {
  filter {
    name   = "label"
    values = ["bastion"]
  }
}
```

### Debug Output

```
data.linode_images.bastion: Reading...
data.linode_images.bastion: Read complete after 0s [id=hu7HcHrt27wlqjJ7zw3Jjvp0Zen+BNs77XLZnetTw7zp48vIcnT8tVr3poVb3i/jCPJ5LKk2fk8DveCNKMjpXA==]
```
```
│ Error: Error creating a Linode Instance: [400] [image] image is not valid
│ 
│   with module.bastion.linode_instance.bastion,
│   on modules/bastion/main.tf line 1, in resource "linode_instance" "bastion":
│    1: resource "linode_instance" "bastion" {
```

Expected OUTPUT = private/XXXXXXXX

### Expected Behavior

Expected OUTPUT = private/XXXXXXXX
When generate the image with Packer this is the output value. If i put this string on a linode_instance on filed image, it accept private/XXXXXXXX

### Actual Behavior

Is picking a wrong Value

### Steps to Reproduce

```
module "bastion" {
  source          = "./modules/bastion"
  image_id      = data.linode_images.bastion.id
  region           = var.region
  type              = "g6-standard-1"
  label             = "bastion"
  swap_size    = 256
  tags              = var.tags
  private_ip     = true
  booted          = true
}
```
https://github.com/jveraduran/terraform-linode-lke

**Comment by LBGarber** [comment]
@jveraduran Thanks for the detailed report!

It looks like the `bastion` module is referencing the data source's internal ID rather than the returned image's ID. Since the `linode_images` data source can return multiple values, it exposes an `images` set with all the images that meet the given conditions.

For example, you can obtain the ID for the first image found using the following snippet:

```
data.linode_images.bastion.images[0].id
```

It looks like the documentation wasn't super clear on this, so I'll see what I can do about adding some clarity.

Let me know if you run into any other issues :slightly_smiling_face:

**Comment by jveraduran** [comment]
Thanks  @LBGarber works now =)
```
data.linode_images.bastion: Reading...
data.linode_images.bastion: Read complete after 0s [id=hu7HcHrt27wlqjJ7zw3Jjvp0Zen+BNs77XLZnetTw7zp48vIcnT8tVr3poVb3i/jCPJ5LKk2fk8DveCNKMjpXA==]

Changes to Outputs:
  + images = "private/17169408"

You can apply this plan to save these new output values to the Terraform state, without changing any real
infrastructure.
```
