### ISSUE TITLE
[Bug]: linode_volume failed to create disk and 

### ISSUE THREAD

**Issue by vkamlesh** [linode/terraform-provider-linode#707]
### Terraform Version

1.3.0

### Linode Provider Version

1.29.2

### Effected Terraform Resources

linode_sshkey
linode_volume

### Terraform Config Files

**Instance.tf**

resource "random_string" "vm-name" {
  length = 4
  upper = false
  numeric = false
  lower = true
  special = false
}

data "linode_profile" "pro-eng" {}

locals {
  vm-name = "${random_string.vm-name.result}-vm"
}

resource "linode_instance" "instance" {
  region = var.region
  label =  "pe-${var.label}-${local.vm-name}"
  group = "pe-${var.label}"
  tags = var.tags
  type = var.machine_type
  private_ip = true
  alerts {
    cpu = 80
  }
}

resource "linode_instance_config" "vm-config" {
  linode_id = linode_instance.instance.id
  label = "pe-vm-config-${var.label}"

  devices {
    sda {
      disk_id = linode_instance_disk.boot_disk.id
    }

    sdb {
      disk_id = linode_volume.data_disk.id
    }

  }

  interface {
    purpose = "public"
    label = "pe-${var.label}-public-interface"
  }

  interface {
    purpose = "vlan"
    label = "pe-${var.label}-private}"
  }
}

resource "linode_volume" "data_disk" {
  label = "pe-data-${var.label}-${local.vm-name}"
  region = linode_instance.instance.region
  size   = 50
  linode_id = linode_instance.instance.id
  tags = ["Data-Disk"]

}

resource "linode_instance_disk" "boot_disk" {
  label = "pe-boot-${var.label}-${local.vm-name}"
  linode_id = linode_instance.instance.id
  size   = 50
  image = "linode/ubuntu22.04"
  authorized_keys = [linode_sshkey.ssh_key.id]
  authorized_users = [data.linode_profile.pro-eng.username]
}

**ssh_key.tf**

resource "random_string" "name" {
  length = 4
  upper = false
  numeric = false
  lower = true
  special = false
}

resource "linode_sshkey" "ssh_key" {
  label = "pe-${var.label}-${random_string.name.result}}"
  ssh_key = "chomp(file(.key/linode.pub))"
}

### Expected Behavior

All resources should be created.

### Actual Behavior

╷
│ Error: failed to create volume: failed to create linode volume: [400] Couldn't choose a configuration profile to add this volume to. Please add this volume to the configuration profile you want.
│ 
│   with module.instance.linode_volume.data_disk,
│   on core/instance/instance.tf line 57, in resource "linode_volume" "data_disk":
│   57: resource "linode_volume" "data_disk" {
│ 
╵
╷
│ Error: Error creating a Linode SSH Key: [400] [label] Labels may only contain letters, number, dashes, and underscores.; [ssh_key] SSH Key key-type must be ssh-dss, ssh-rsa, ecdsa-sha2-nistp, or ssh-ed25519.
│ 
│   with module.instance.linode_sshkey.ssh_key,
│   on core/instance/ssh_key.tf line 10, in resource "linode_sshkey" "ssh_key":
│   10: resource "linode_sshkey" "ssh_key" {
│ 

### Steps to Reproduce

Use the above terraform code and run terraform plan.

**Comment by LBGarber** [comment]
@vkamlesh Thanks for the report!
There seem to be a few issues with your config that are causing these errors:

 1. Since you're including the `volume_id` in the `linode_instance_config` definition, you'll need to remove this line from the `linode_volume` resource:
 
 ```hcl
linode_id = linode_instance.instance.id
```

This is because volumes are created as independent resources and are automatically attached to a Linode if specified in the `linode_instance_config`.

3. It looks like there are a few small typos in the `linode_sshkey` definition. The configuration should look like this:

```hcl
resource "linode_sshkey" "ssh_key" {
  label = "pe-${var.label}-${random_string.name.result}"
  ssh_key = chomp(file(".key/linode.pub"))
}
```

4. When creating the `linode_instance_disk`, the `authorized_keys` field should reference the `ssh_key` field of the `linode_sshkey` resource defined earlier:

```hcl
authorized_keys = [linode_sshkey.ssh_key.ssh_key]
``` 

Additionally, this resource requires a `root_pass` to be defined.

5. When creating a public interface, the `label` field should be excluded. At the moment, interface labels are only used to identify the VLAN to join by name. It looks like our documentation isn't quite clear on this, so I'll put up a PR to add some clarity.

6. In the `sdb` device in `linode_instance_config`, it looks like you're referencing the volume by `disk_id` rather than `volume_id`.

Let me know if you run into any other issues :slightly_smiling_face:

**Comment by LBGarber** [comment]
Closing this issue since it seems like everything is working as expected. Feel free to @ me if this issue is still occurring :slightly_smiling_face:
